# Generated by Django 5.1.15 on 2026-02-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ico', models.CharField(db_index=True, max_length=8, unique=True)),
                ('business_name', models.CharField(max_length=500)),
                ('raw_data', models.JSONField(default=dict)),
            ],
        ),
    ]
