# Generated by Django 5.1.15 on 2026-02-27 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='employee_category',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='latest_revenue',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='legal_form',
            field=models.CharField(blank=True, db_index=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='nace_primary',
            field=models.CharField(blank=True, db_index=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='region_code',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='region_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['legal_form', 'region_code'], name='idx_company_form_region'),
        ),
    ]
