# Generated by Django 5.1.15 on 2026-02-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourtRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ico', models.CharField(db_index=True, max_length=20)),
                ('document_id', models.CharField(max_length=100)),
                ('document_type', models.CharField(blank=True, default='', max_length=50)),
                ('parsed_data', models.JSONField(blank=True, default=dict)),
                ('source_url', models.URLField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('ico', 'document_id')},
            },
        ),
    ]
