# Generated by Django 5.1.15 on 2026-02-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justice', '0002_opendata_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='address',
            new_name='justice_add_municip_318c9f_idx',
            old_name='justice_addr_muni_idx',
        ),
        migrations.RenameIndex(
            model_name='address',
            new_name='justice_add_postal__10c377_idx',
            old_name='justice_addr_psc_idx',
        ),
        migrations.RenameIndex(
            model_name='datasetsync',
            new_name='justice_dat_status_3fb799_idx',
            old_name='justice_ds_status_idx',
        ),
        migrations.RenameIndex(
            model_name='datasetsync',
            new_name='justice_dat_legal_f_43f190_idx',
            old_name='justice_ds_lf_loc_idx',
        ),
        migrations.RenameIndex(
            model_name='datasetsync',
            new_name='justice_dat_last_sy_5f5313_idx',
            old_name='justice_ds_synced_idx',
        ),
        migrations.RenameIndex(
            model_name='entity',
            new_name='justice_ent_name_b4bac5_idx',
            old_name='justice_ent_name_idx',
        ),
        migrations.RenameIndex(
            model_name='entity',
            new_name='justice_ent_legal_f_aec056_idx',
            old_name='justice_ent_lf_idx',
        ),
        migrations.RenameIndex(
            model_name='entity',
            new_name='justice_ent_court_c_9e3592_idx',
            old_name='justice_ent_court_idx',
        ),
        migrations.RenameIndex(
            model_name='entity',
            new_name='justice_ent_is_acti_45aa54_idx',
            old_name='justice_ent_active_idx',
        ),
        migrations.RenameIndex(
            model_name='entityfact',
            new_name='justice_ent_entity__97e33f_idx',
            old_name='justice_fact_ent_type_idx',
        ),
        migrations.RenameIndex(
            model_name='person',
            new_name='justice_per_last_na_7d3236_idx',
            old_name='justice_person_name_idx',
        ),
        migrations.RenameIndex(
            model_name='person',
            new_name='justice_per_entity__2316c8_idx',
            old_name='justice_person_ico_idx',
        ),
        migrations.AlterField(
            model_name='address',
            name='evidence_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='house_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='number_text',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='orientation_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
