# Generated by Django 5.1.15 on 2026-02-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justice', '0003_rename_justice_addr_muni_idx_justice_add_municip_318c9f_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='file_reference',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='entity',
            name='file_section',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='entityfact',
            name='fact_type_code',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='entity_ico',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='entity_name',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='person',
            name='euid',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='person',
            name='reg_number',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='person',
            name='title_after',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='title_before',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
