# Generated by Django 5.1.15 on 2026-02-27 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('justice', '0005_pad_ico_leading_zeros'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='justice_entities', to='company.company'),
        ),
    ]
