/**
 * Reference data for Justice search form dropdowns.
 * Mirrors backend/justice/constants.py LEGAL_FORMS and COURT_LOCATIONS.
 */

export const JUSTICE_LEGAL_FORMS = [
  { code: "sro", name: "Společnost s ručením omezeným" },
  { code: "as", name: "Akciová společnost" },
  { code: "spolek", name: "Spolek" },
  { code: "nad", name: "Nadace" },
  { code: "ks", name: "Komanditní společnost" },
  { code: "vos", name: "Veřejná obchodní společnost" },
  { code: "svj", name: "Společenství vlastníků jednotek" },
  { code: "dr", name: "Družstvo" },
  { code: "nadacni_fond", name: "Nadační fond" },
  { code: "ustav", name: "Ústav" },
  { code: "zspo", name: "Zájmové sdružení právnických osob" },
  { code: "ps", name: "Příspěvková organizace" },
  { code: "op", name: "Obecně prospěšná společnost" },
  { code: "se", name: "Evropská společnost" },
  { code: "sce", name: "Evropská družstevní společnost" },
  { code: "ehzs", name: "Evropské hospodářské zájmové sdružení" },
  { code: "ksk", name: "Komanditní společnost na akcie" },
  { code: "pobocny_spolek", name: "Pobočný spolek" },
  { code: "zahranicni_fo", name: "Zahraniční fyzická osoba" },
  { code: "zahranicni_po", name: "Zahraniční právnická osoba" },
  { code: "odborova_organizace", name: "Odborová organizace" },
  { code: "organizace_zamestnavatelu", name: "Organizace zaměstnavatelů" },
  { code: "mezinarodni_odborova_organizace", name: "Mezinárodní odborová organizace" },
  { code: "mezinarodni_organizace_zamestnavatelu", name: "Mezinárodní organizace zaměstnavatelů" },
  { code: "pobocna_odborova_organizace", name: "Pobočná odborová organizace" },
  { code: "pobocna_organizace_zamestnavatelu", name: "Pobočná organizace zaměstnavatelů" },
  { code: "pobocna_mezinarodni_odborova_organizace", name: "Pobočná mezinárodní odborová organizace" },
  { code: "pobocna_mezinarodni_organizace_zamestnavatelu", name: "Pobočná mezinárodní organizace zaměstnavatelů" },
  { code: "spolek_transformovany", name: "Spolek transformovaný" },
  { code: "zahranicni_pobocny_spolek", name: "Zahraniční pobočný spolek" },
  { code: "spolecenstvi_vlastniku_jednotek", name: "Společenství vlastníků jednotek" },
  { code: "fundace", name: "Fundace" },
  { code: "sdruzeni", name: "Sdružení" },
  { code: "organizacni_slozka_zahranicniho_fo", name: "Organizační složka zahraničního FO" },
  { code: "organizacni_slozka_zahranicniho_po", name: "Organizační složka zahraničního PO" },
  { code: "zahranicni_svjf", name: "Zahraniční SVJ/Fond" },
  { code: "organizacni_slozka_zahranicni_fo", name: "Organizační složka zahraniční FO" },
  { code: "organizacni_slozka_zahranicni_po", name: "Organizační složka zahraniční PO" },
  { code: "organizacni_slozka_zahranicniho_svjf", name: "Organizační složka zahraničního SVJ/Fond" },
  { code: "organizacni_slozka", name: "Organizační složka" },
  { code: "osoba_povinne_zapisovana", name: "Osoba povinně zapisovaná" },
  { code: "fyzicka_osoba_zapisovana_do_or", name: "Fyzická osoba zapisovaná do OR" },
] as const;

export const JUSTICE_COURT_LOCATIONS = [
  { code: "praha", name: "Městský soud v Praze" },
  { code: "brno", name: "Krajský soud v Brně" },
  { code: "ostrava", name: "Krajský soud v Ostravě" },
  { code: "ceske_budejovice", name: "Krajský soud v Českých Budějovicích" },
  { code: "plzen", name: "Krajský soud v Plzni" },
  { code: "hradec_kralove", name: "Krajský soud v Hradci Králové" },
  { code: "usti_nad_labem", name: "Krajský soud v Ústí nad Labem" },
] as const;
